sudo: required
language: generic
services:
  - docker
before_install:
  - echo "start Creating image with dockerfile.dev"
  - docker build -t jyong9591/docker-react-app -f dockerfile.dev .
script:
  - docker run -e CI=true jyong9591/docker-react-app npm run test -- --coverage
after_success:
  - echo "test success"